#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "mediawikiparser.y".
#

require 'racc/parser'


require 'mediacloth/mediawikiast'


class MediaWikiParser < Racc::Parser

module_eval <<'..end mediawikiparser.y modeval..id2fa3e0400b', 'mediawikiparser.y', 354

attr_accessor :lexer

def initialize
    @nodes = []
    super
end

#Tokenizes input string and parses it.
def parse(input)
    @yydebug=true
    lexer.tokenize(input)
    do_parse
    return @nodes.last
end

#Asks the lexer to return the next token.
def next_token
    return @lexer.lex
end
..end mediawikiparser.y modeval..id2fa3e0400b

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 38, :_reduce_1,
 1, 40, :_reduce_2,
 1, 40, :_reduce_3,
 1, 40, :_reduce_4,
 1, 40, :_reduce_5,
 1, 40, :_reduce_6,
 3, 40, :_reduce_7,
 3, 40, :_reduce_8,
 6, 40, :_reduce_9,
 4, 40, :_reduce_10,
 1, 40, :_reduce_none,
 0, 46, :_reduce_12,
 1, 46, :_reduce_13,
 1, 47, :_reduce_14,
 3, 47, :_reduce_15,
 1, 51, :_reduce_16,
 3, 51, :_reduce_17,
 0, 49, :_reduce_18,
 2, 49, :_reduce_19,
 0, 48, :_reduce_20,
 2, 48, :_reduce_21,
 3, 48, :_reduce_22,
 1, 39, :_reduce_23,
 2, 39, :_reduce_24,
 1, 41, :_reduce_25,
 1, 41, :_reduce_26,
 3, 50, :_reduce_27,
 4, 50, :_reduce_28,
 0, 54, :_reduce_29,
 4, 54, :_reduce_30,
 5, 54, :_reduce_31,
 0, 55, :_reduce_32,
 3, 55, :_reduce_33,
 4, 55, :_reduce_34,
 3, 55, :_reduce_35,
 4, 55, :_reduce_36,
 1, 52, :_reduce_37,
 1, 52, :_reduce_38,
 1, 52, :_reduce_39,
 1, 52, :_reduce_40,
 1, 52, :_reduce_41,
 2, 53, :_reduce_42,
 2, 53, :_reduce_43,
 3, 53, :_reduce_44,
 3, 53, :_reduce_45,
 4, 42, :_reduce_46,
 4, 43, :_reduce_47,
 0, 58, :_reduce_48,
 3, 57, :_reduce_49,
 0, 57, :_reduce_50,
 2, 56, :_reduce_51,
 3, 56, :_reduce_52,
 1, 44, :_reduce_53,
 3, 45, :_reduce_54 ]

racc_reduce_n = 55

racc_shift_n = 100

racc_action_table = [
     4,    57,     7,    54,    14,   -48,    36,    23,    57,    72,
    54,     3,    32,     8,     9,    12,    16,    18,    21,    25,
    37,    62,    63,     6,     4,    10,     7,    57,    14,    54,
    56,    23,    57,     5,    54,     3,    37,     8,     9,    12,
    16,    18,    21,    25,   -50,    47,    57,     6,    54,    10,
    79,     4,    28,     7,    57,    14,    54,     5,    23,    80,
    81,    69,     3,    58,     8,     9,    12,    16,    18,    21,
    25,    32,    37,    86,     6,     4,    10,     7,    43,    14,
    59,    41,    23,    39,     5,    90,     3,   -50,     8,     9,
    12,    16,    18,    21,    25,    37,    60,    61,     6,    32,
    10,    98,     4,    67,     7,   nil,    14,   nil,     5,    23,
   nil,    90,   nil,     3,   nil,     8,     9,    12,    16,    18,
    21,    25,   nil,   nil,   nil,     6,     4,    10,     7,    34,
    14,   nil,   nil,    23,   nil,     5,   nil,     3,   nil,     8,
     9,    12,    16,    18,    21,    25,   nil,   nil,   nil,     6,
     4,    10,     7,   nil,    14,   nil,   nil,    23,   nil,     5,
   nil,     3,   nil,     8,     9,    12,    16,    18,    21,    25,
   nil,   nil,   nil,     6,     4,    10,     7,   nil,    14,   nil,
   nil,    23,   nil,     5,   nil,     3,   nil,     8,     9,    12,
    16,    18,    21,    25,   nil,   nil,   nil,     6,     4,    10,
     7,   nil,    14,   nil,    89,    23,   nil,     5,   nil,     3,
   nil,     8,     9,    12,    16,    18,    21,    25,   nil,   nil,
   nil,     6,     4,    10,     7,   nil,    14,   nil,   nil,    23,
   nil,     5,   nil,     3,   nil,     8,     9,    12,    16,    18,
    21,    25,   nil,   nil,   nil,     6,     4,    10,     7,   nil,
    14,   nil,   nil,    23,   nil,     5,   nil,     3,   nil,     8,
     9,    12,    16,    18,    21,    25,   nil,   nil,   nil,     6,
     4,    10,     7,   nil,    14,   nil,    87,    23,   nil,     5,
   nil,     3,   nil,     8,     9,    12,    16,    18,    21,    25,
   nil,   nil,   nil,     6,     4,    10,     7,   nil,    14,   nil,
   nil,    23,    84,     5,   nil,     3,    45,     8,     9,    12,
    16,    18,    21,    25,   nil,   nil,   nil,     6,   nil,    10,
   nil,     4,    46,     7,   nil,    14,   nil,     5,    23,   nil,
   nil,   nil,     3,   nil,     8,     9,    12,    16,    18,    21,
    25,   nil,   nil,   nil,     6,     4,    10,     7,   nil,    14,
   nil,   nil,    23,   nil,     5,   nil,     3,   nil,     8,     9,
    12,    16,    18,    21,    25,   nil,   nil,   nil,     6,     4,
    10,     7,   nil,    14,   nil,   nil,    23,   nil,     5,   nil,
     3,   nil,     8,     9,    12,    16,    18,    21,    25,   nil,
   nil,   nil,     6,     4,    10,     7,   nil,    14,   nil,   nil,
    23,   nil,     5,   nil,     3,   nil,     8,     9,    12,    16,
    18,    21,    25,   nil,   nil,    48,     6,     4,    10,     7,
   nil,    14,   nil,   nil,    23,   nil,     5,   nil,     3,   nil,
     8,     9,    12,    16,    18,    21,    25,   nil,   nil,   nil,
     6,     4,    10,     7,    52,    14,   nil,   nil,    23,   nil,
     5,   nil,     3,   nil,     8,     9,    12,    16,    18,    21,
    25,   nil,   nil,   nil,     6,     4,    10,     7,   nil,    14,
   nil,   nil,    23,   nil,     5,   nil,     3,   nil,     8,     9,
    12,    16,    18,    21,    25,   nil,   nil,   nil,     6,     4,
    10,     7,   nil,    14,   nil,    75,    23,   nil,     5,   nil,
     3,   nil,     8,     9,    12,    16,    18,    21,    25,   nil,
   nil,   nil,     6,     4,    10,     7,   nil,    14,   nil,   nil,
    23,    70,     5,   nil,     3,   nil,     8,     9,    12,    16,
    18,    21,    25,   nil,   nil,    66,     6,   nil,    10,   nil,
     4,   nil,     7,   nil,    14,   nil,     5,    23,   nil,    90,
   nil,     3,   nil,     8,     9,    12,    16,    18,    21,    25,
   nil,   nil,   nil,     6,   nil,    10,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     5 ]

racc_action_check = [
     0,    84,     0,    84,     0,    68,    10,     0,    87,    55,
    87,     0,    51,     0,     0,     0,     0,     0,     0,     0,
    10,    43,    43,     0,     3,     0,     3,    56,     3,    56,
    37,     3,    70,     0,    70,     3,    36,     3,     3,     3,
     3,     3,     3,     3,    33,    30,    37,     3,    37,     3,
    63,     4,     4,     4,    75,     4,    75,     3,     4,    64,
    65,    53,     4,    38,     4,     4,     4,     4,     4,     4,
     4,    25,    72,    73,     4,     5,     4,     5,    23,     5,
    39,    14,     5,    11,     4,    79,     5,    44,     5,     5,
     5,     5,     5,     5,     5,    86,    40,    41,     5,     6,
     5,    91,    90,    50,    90,   nil,    90,   nil,     5,    90,
   nil,    90,   nil,    90,   nil,    90,    90,    90,    90,    90,
    90,    90,   nil,   nil,   nil,    90,     7,    90,     7,     7,
     7,   nil,   nil,     7,   nil,    90,   nil,     7,   nil,     7,
     7,     7,     7,     7,     7,     7,   nil,   nil,   nil,     7,
    89,     7,    89,   nil,    89,   nil,   nil,    89,   nil,     7,
   nil,    89,   nil,    89,    89,    89,    89,    89,    89,    89,
   nil,   nil,   nil,    89,    78,    89,    78,   nil,    78,   nil,
   nil,    78,   nil,    89,   nil,    78,   nil,    78,    78,    78,
    78,    78,    78,    78,   nil,   nil,   nil,    78,    76,    78,
    76,   nil,    76,   nil,    76,    76,   nil,    78,   nil,    76,
   nil,    76,    76,    76,    76,    76,    76,    76,   nil,   nil,
   nil,    76,    15,    76,    15,   nil,    15,   nil,   nil,    15,
   nil,    76,   nil,    15,   nil,    15,    15,    15,    15,    15,
    15,    15,   nil,   nil,   nil,    15,    74,    15,    74,   nil,
    74,   nil,   nil,    74,   nil,    15,   nil,    74,   nil,    74,
    74,    74,    74,    74,    74,    74,   nil,   nil,   nil,    74,
    71,    74,    71,   nil,    71,   nil,    74,    71,   nil,    74,
   nil,    71,   nil,    71,    71,    71,    71,    71,    71,    71,
   nil,   nil,   nil,    71,    27,    71,    27,   nil,    27,   nil,
   nil,    27,    71,    71,   nil,    27,    27,    27,    27,    27,
    27,    27,    27,    27,   nil,   nil,   nil,    27,   nil,    27,
   nil,    29,    29,    29,   nil,    29,   nil,    27,    29,   nil,
   nil,   nil,    29,   nil,    29,    29,    29,    29,    29,    29,
    29,   nil,   nil,   nil,    29,    62,    29,    62,   nil,    62,
   nil,   nil,    62,   nil,    29,   nil,    62,   nil,    62,    62,
    62,    62,    62,    62,    62,   nil,   nil,   nil,    62,    31,
    62,    31,   nil,    31,   nil,   nil,    31,   nil,    62,   nil,
    31,   nil,    31,    31,    31,    31,    31,    31,    31,   nil,
   nil,   nil,    31,    32,    31,    32,   nil,    32,   nil,   nil,
    32,   nil,    31,   nil,    32,   nil,    32,    32,    32,    32,
    32,    32,    32,   nil,   nil,    32,    32,    61,    32,    61,
   nil,    61,   nil,   nil,    61,   nil,    32,   nil,    61,   nil,
    61,    61,    61,    61,    61,    61,    61,   nil,   nil,   nil,
    61,    35,    61,    35,    35,    35,   nil,   nil,    35,   nil,
    61,   nil,    35,   nil,    35,    35,    35,    35,    35,    35,
    35,   nil,   nil,   nil,    35,    57,    35,    57,   nil,    57,
   nil,   nil,    57,   nil,    35,   nil,    57,   nil,    57,    57,
    57,    57,    57,    57,    57,   nil,   nil,   nil,    57,    54,
    57,    54,   nil,    54,   nil,    57,    54,   nil,    57,   nil,
    54,   nil,    54,    54,    54,    54,    54,    54,    54,   nil,
   nil,   nil,    54,    49,    54,    49,   nil,    49,   nil,   nil,
    49,    54,    54,   nil,    49,   nil,    49,    49,    49,    49,
    49,    49,    49,   nil,   nil,    49,    49,   nil,    49,   nil,
    97,   nil,    97,   nil,    97,   nil,    49,    97,   nil,    97,
   nil,    97,   nil,    97,    97,    97,    97,    97,    97,    97,
   nil,   nil,   nil,    97,   nil,    97,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    97 ]

racc_action_pointer = [
    -2,   nil,   nil,    22,    49,    73,    76,   124,   nil,   nil,
    -9,    83,   nil,   nil,    66,   220,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    63,   nil,    48,   nil,   292,   nil,   319,
     9,   367,   391,    18,   nil,   439,     7,    15,    35,    80,
    89,    89,   nil,    10,    65,   nil,   nil,   nil,   nil,   511,
    77,   -11,   nil,    33,   487,   -21,    -4,   463,   nil,   nil,
   nil,   415,   343,    35,    49,    38,   nil,   nil,   -18,   nil,
     1,   268,    43,    43,   244,    23,   196,   nil,   172,    74,
   nil,   nil,   nil,   nil,   -30,   nil,    66,   -23,   nil,   148,
   100,    91,   nil,   nil,   nil,   nil,   nil,   538,   nil,   nil ]

racc_action_default = [
   -55,    -5,    -6,   -55,   -55,   -12,   -55,   -55,   -37,   -53,
   -29,   -55,   -38,   -11,   -55,    -1,   -40,   -23,   -39,   -25,
    -2,   -41,   -26,   -55,    -3,   -55,    -4,   -55,   -42,   -55,
   -55,   -13,   -55,   -48,   -43,   -55,   -29,   -32,   -55,   -55,
   -55,   -14,   -24,   -18,   -48,   -54,   -44,    -7,   -51,   -55,
   -55,   -55,   -45,   -55,   -55,   -55,   -32,   -55,   -27,   100,
    -8,   -55,   -55,   -55,   -55,   -55,   -52,   -47,   -50,   -28,
   -32,   -55,   -29,   -55,   -55,   -32,   -16,   -15,   -19,   -20,
   -10,   -46,   -49,   -35,   -32,   -30,   -29,   -32,   -33,   -55,
   -20,   -55,   -36,   -31,   -34,   -17,   -21,   -20,    -9,   -22 ]

racc_goto_table = [
    15,    55,    42,    27,    29,    31,    50,    35,    33,    38,
    77,    64,    91,    40,    42,    30,    42,    65,    42,    11,
    73,   nil,    42,    96,   nil,   nil,   nil,    44,   nil,   nil,
    99,   nil,    49,   nil,    83,    53,    42,   nil,    95,    88,
   nil,    82,   nil,   nil,   nil,   nil,   nil,   nil,    92,   nil,
   nil,    94,   nil,    68,    71,   nil,   nil,    74,    42,   nil,
   nil,    42,    78,    42,   nil,    42,   nil,   nil,   nil,   nil,
   nil,    85,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    42,    93,   nil,   nil,   nil,   nil,
    97 ]

racc_goto_check = [
     2,    18,     3,     2,     2,     2,    20,     2,    19,    17,
    14,    12,    11,    10,     3,     9,     3,    20,     3,     1,
    18,   nil,     3,    11,   nil,   nil,   nil,    19,   nil,   nil,
    11,   nil,     2,   nil,    18,    17,     3,   nil,    14,    18,
   nil,    20,   nil,   nil,   nil,   nil,   nil,   nil,    18,   nil,
   nil,    18,   nil,    19,     2,   nil,   nil,     2,     3,   nil,
   nil,     3,     2,     3,   nil,     3,   nil,   nil,   nil,   nil,
   nil,    17,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     3,    17,   nil,   nil,   nil,   nil,
     2 ]

racc_goto_pointer = [
   nil,    19,     0,   -13,   nil,   nil,   nil,   nil,   nil,    10,
    -1,   -67,   -32,   nil,   -51,   nil,   nil,    -1,   -36,     2,
   -27,   nil ]

racc_goto_default = [
   nil,   nil,    76,    17,    20,    24,    26,     1,     2,   nil,
   nil,   nil,   nil,    13,   nil,    19,    22,   nil,   nil,   nil,
   nil,    51 ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :BOLDSTART => 2,
 :BOLDEND => 3,
 :ITALICSTART => 4,
 :ITALICEND => 5,
 :LINKSTART => 6,
 :LINKEND => 7,
 :LINKSEP => 8,
 :INTLINKSTART => 9,
 :INTLINKEND => 10,
 :INTLINKSEP => 11,
 :RESOURCE_SEP => 12,
 :SECTION_START => 13,
 :SECTION_END => 14,
 :TEXT => 15,
 :PRE => 16,
 :HLINE => 17,
 :SIGNATURE_NAME => 18,
 :SIGNATURE_DATE => 19,
 :SIGNATURE_FULL => 20,
 :UL_START => 21,
 :UL_END => 22,
 :LI_START => 23,
 :LI_END => 24,
 :OL_START => 25,
 :OL_END => 26,
 :TABLE_START => 27,
 :TABLE_END => 28,
 :ROW_START => 29,
 :ROW_END => 30,
 :HEAD_START => 31,
 :HEAD_END => 32,
 :CELL_START => 33,
 :CELL_END => 34,
 :PARA_START => 35,
 :PARA_END => 36 }

racc_use_result_var = true

racc_nt_base = 37

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'BOLDSTART',
'BOLDEND',
'ITALICSTART',
'ITALICEND',
'LINKSTART',
'LINKEND',
'LINKSEP',
'INTLINKSTART',
'INTLINKEND',
'INTLINKSEP',
'RESOURCE_SEP',
'SECTION_START',
'SECTION_END',
'TEXT',
'PRE',
'HLINE',
'SIGNATURE_NAME',
'SIGNATURE_DATE',
'SIGNATURE_FULL',
'UL_START',
'UL_END',
'LI_START',
'LI_END',
'OL_START',
'OL_END',
'TABLE_START',
'TABLE_END',
'ROW_START',
'ROW_END',
'HEAD_START',
'HEAD_END',
'CELL_START',
'CELL_END',
'PARA_START',
'PARA_END',
'$start',
'wiki',
'repeated_contents',
'contents',
'text',
'bulleted_list',
'numbered_list',
'preformatted',
'section',
'para_contents',
'link_contents',
'reslink_repeated_contents',
'intlink_repeated_contents',
'table',
'link_repeated_contents',
'element',
'formatted_element',
'table_contents',
'row_contents',
'list_item',
'list_contents',
'@1']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'mediawikiparser.y', 29
  def _reduce_1( val, _values, result )
            @nodes.push WikiAST.new
            #@nodes.last.children.insert(0, val[0])
            #puts val[0]
            @nodes.last.children += val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 36
  def _reduce_2( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 40
  def _reduce_3( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 44
  def _reduce_4( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 50
  def _reduce_5( val, _values, result )
            p = PreformattedAST.new
            p.contents = val[0]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 54
  def _reduce_6( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 62
  def _reduce_7( val, _values, result )
            if val[1]
                p = ParagraphAST.new
                p.children = val[1]
                result = p
            end
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 69
  def _reduce_8( val, _values, result )
            l = LinkAST.new
            l.url = val[1][0]
            l.children += val[1][1..-1] if val[1].length > 1
            result = l
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 77
  def _reduce_9( val, _values, result )
            l = ResourceLinkAST.new
            l.prefix = val[1]
            l.locator = val[3]
            l.children = val[4] unless val[4].nil? or val[4].empty?
            result = l
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 84
  def _reduce_10( val, _values, result )
            l = InternalLinkAST.new
            l.locator = val[1]
            l.children = val[2] unless val[2].nil? or val[2].empty?
            result = l
   result
  end
.,.,

 # reduce 11 omitted

module_eval <<'.,.,', 'mediawikiparser.y', 92
  def _reduce_12( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 96
  def _reduce_13( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 103
  def _reduce_14( val, _values, result )
            result = val
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 108
  def _reduce_15( val, _values, result )
            result = [val[0]]
            result += val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 116
  def _reduce_16( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 121
  def _reduce_17( val, _values, result )
            result = val[0]
            result += val[2] if val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 128
  def _reduce_18( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 132
  def _reduce_19( val, _values, result )
            result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 138
  def _reduce_20( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 142
  def _reduce_21( val, _values, result )
            result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 149
  def _reduce_22( val, _values, result )
            i = InternalLinkItemAST.new
            i.children = val[1]
            result = [i]
            result += val[2] if val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 156
  def _reduce_23( val, _values, result )
            result = []
            result << val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 162
  def _reduce_24( val, _values, result )
            result = []
            result += val[0]
            result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 171
  def _reduce_25( val, _values, result )
            p = TextAST.new
            p.formatting = val[0][0]
            p.contents = val[0][1]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 175
  def _reduce_26( val, _values, result )
            result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 184
  def _reduce_27( val, _values, result )
            table = TableAST.new
            table.children = val[1] unless val[1].nil? or val[1].empty?
            result = table
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 191
  def _reduce_28( val, _values, result )
            table = TableAST.new
            table.options = val[1]
            table.children = val[2] unless val[2].nil? or val[2].empty?
            result = table
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 196
  def _reduce_29( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 203
  def _reduce_30( val, _values, result )
            row = TableRowAST.new
            row.children = val[1] unless val[1].nil? or val[1].empty?
            result = [row]
            result += val[3] unless val[3].nil? or val[3].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 211
  def _reduce_31( val, _values, result )
            row = TableRowAST.new
            row.children = val[2] unless val[2].nil? or val[2].empty?
            row.options = val[1]
            result = [row]
            result += val[4] unless val[4].nil? or val[4].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 216
  def _reduce_32( val, _values, result )
            result = nil
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 223
  def _reduce_33( val, _values, result )
            cell = TableCellAST.new
            cell.type = :head
            result = [cell]
            result += val[2] unless val[2].nil? or val[2].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 231
  def _reduce_34( val, _values, result )
            cell = TableCellAST.new
            cell.children = val[1] unless val[1].nil? or val[1].empty?
            cell.type = :head
            result = [cell]
            result += val[3] unless val[3].nil? or val[3].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 238
  def _reduce_35( val, _values, result )
            cell = TableCellAST.new
            cell.type = :body
            result = [cell]
            result += val[2] unless val[2].nil? or val[2].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 246
  def _reduce_36( val, _values, result )
            cell = TableCellAST.new
            cell.children = val[1] unless val[1].nil? or val[1].empty?
            cell.type = :body
            result = [cell]
            result += val[3] unless val[3].nil? or val[3].empty?
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 250
  def _reduce_37( val, _values, result )
 return [:None, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 252
  def _reduce_38( val, _values, result )
 return [:HLine, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 254
  def _reduce_39( val, _values, result )
 return [:SignatureDate, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 256
  def _reduce_40( val, _values, result )
 return [:SignatureName, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 258
  def _reduce_41( val, _values, result )
 return [:SignatureFull, val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 268
  def _reduce_42( val, _values, result )
            result = FormattedAST.new
            result.formatting = :Bold
            result
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 274
  def _reduce_43( val, _values, result )
            result = FormattedAST.new
            result.formatting = :Italic
            result
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 281
  def _reduce_44( val, _values, result )
            p = FormattedAST.new
            p.formatting = :Bold
            p.children += val[1]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 288
  def _reduce_45( val, _values, result )
            p = FormattedAST.new
            p.formatting = :Italic
            p.children += val[1]
            result = p
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 298
  def _reduce_46( val, _values, result )
            list = ListAST.new
            list.list_type = :Bulleted
            list.children << val[1]
            list.children += val[2]
            result = list
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 308
  def _reduce_47( val, _values, result )
            list = ListAST.new
            list.list_type = :Numbered
            list.children << val[1]
            list.children += val[2]
            result = list
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 311
  def _reduce_48( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 317
  def _reduce_49( val, _values, result )
            result << val[1]
            result += val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 318
  def _reduce_50( val, _values, result )
 result = []
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 326
  def _reduce_51( val, _values, result )
            result = ListItemAST.new
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 332
  def _reduce_52( val, _values, result )
            li = ListItemAST.new
            li.children += val[1]
            result = li
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 335
  def _reduce_53( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'mediawikiparser.y', 344
  def _reduce_54( val, _values, result )
 result = [val[1], val[0].length] 
            s = SectionAST.new
            s.children = val[1]
            s.level = val[0].length
            result = s
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

end   # class MediaWikiParser
